# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

# -------------------------------------------------------------------------------
# Site settings
# -------------------------------------------------------------------------------
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "André L. Maravilha"

author:
  name: "André L. Maravilha"
  email: "andre.maravilha@outlook.com"

description: 
  en: "André L. Maravilha's personal website"
  pt:BR: "Página de André L. Maravilha"

baseurl: ""
url: "https://andremaravilha.github.io/"

lattes: "http://lattes.cnpq.br/9685472895445408"
orcid: "https://orcid.org/0000-0002-5869-3052"
linkedin: "https://linkedin.com/in/andremaravilha"
github:  "https://github.com/andremaravilha"
instagram: "https://www.instagram.com/andrelmaravilha/"


# -------------------------------------------------------------------------------
# Build settings
# -------------------------------------------------------------------------------

#theme: minima

include: 
  - .htaccess

sass:
  sass_dir: assets/stylesheets

plugins:
  - jekyll-polyglot
  - jekyll-node-module

# jekyll-polyglot settings
languages: ["pt_BR", "en"]
default_lang: "pt_BR"
exclude_from_localization: ["assets"]
lang_from_path: true
parallel_localization: false

# jekyll-node-modules settings
node_modules:
  assets:
    js: assets/js
    css: assets/css
  copy:
  - source: "@fortawesome/fontawesome-free/webfonts"
    target: "assets/webfonts"
  - source: "bootstrap-icons/font/fonts"
    target: "assets/css/fonts"
  - source: "academicons/fonts"
    target: "assets/fonts"


# -------------------------------------------------------------------------------
# Exclude from processing.
# -------------------------------------------------------------------------------
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - package-lock.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - .github/
  - .gitignore
